### ISSUE TITLE
Apparent Bug in formgen.py

### ISSUE THREAD

**Issue by morey18k** [bfichera/shgpy#1]
In lines 284-286 of formgen.py, in the function `gen_S`, I noticed an apparent error when trying to validate my SHG code with the results given by SHGPy. `gen_S` is used to generate the formulas in the black box function `formgen` as of recently, making this issue somewhat urgent.

The code that is written as is reads

`rt_qee = tensor_contract(
            tensor_product(R, R, R, t_qee),
            [[1, 6], [3, 7], [5, 8]],
        ) `

This *should* be

`rt_qee = tensor_contract(
            tensor_product(R, R, R, R, t_qee),
            [[1, 8], [3, 9], [5, 10],[7,11]],
        ) `

This is because quadrupole tensors are fourth rank, thus transform with one rotation matrix per index, i.e. 4. All the other transformations in `gen_S` seem to be correct, but this one potentially needs a closer look.

Could you advise @bfichera?

**Comment by bfichera** [comment]
This is correct, looks like an unfortunate copy paste error when we switched over to gen_S. I will push out a fix shortly. Thanks @morey18k!
